spring:
  redis:
    database: 0
    host: dreamatach.com
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        max-wait: -1ms
        min-idle: 0
    password: dreamatach.com
    port: 6379
